
name: Profile Readme

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate README
        uses: actions-js/profile-readme@v1
        with:
          username: amirhossein
          github_token: ${{ secrets.GITHUB_TOKEN }}
          template: ./TEMPLATE.md
          readme: ./README.md

      - name: Commit and Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
